import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import { DeviceProvider } from "@/shared/context/deviceContext";

export const metadata: Metadata = {
  title: "Slider example",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DeviceProvider>
          <Header />
          {children}
        </DeviceProvider>
      </body>
    </html>
  );
}
